spring.application.name=Nump

# 1. Configuração do Data Source
# No Render, ele usará as variáveis. Localmente, usará o H2.
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USER:sa}
spring.datasource.password=${DATABASE_PASS:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}

# 2. Configuração do Hibernate (O segredo para matar o erro de Dialect)
# Esta linha força o dialeto correto baseado na variável que você deve criar no Render
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update

# 3. H2 Console (Apenas para teste local)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. Segurança JWT
jwt.secret=${JWT_SECRET:8f3c9e12ab45cd78ef90gh12ij34kl56}
jwt.expiration=86400000